image: nvcr.io/nvidia/cuda:11.0-devel-ubuntu18.04

variables:
  GIT_SUBMODULE_STRATEGY: recursive

default:
  before_script:
    - apt-get update && apt-get install -qy cmake

# make sure there aren't any left over notes saying "delete me"
no_debugging_notes:
  stage: build
  tags:
    - os/linux
  only:
    - merge_requests
  script:
    - if grep -snHI "delete me" $(for ext in c h cpp cu cuh; do find -name "*.${ext}"; done); then exit 1; else exit 0; fi

build_debug_linux:
  stage: build
  tags:
    - os/linux
  only:
    - merge_requests
  script:
    - mkdir build
    - cd build/ && cmake ../ -DDEVEL=1 -DCMAKE_BUILD_TYPE=Debug -DCMAKE_VERBOSE_MAKEFILE=1 && make -j$(grep -c ^processor /proc/cpuinfo)

build_release_linux:
  stage: build
  tags:
    - os/linux
  only:
    - merge_requests
  script:
    - mkdir build
    - cd build/ && cmake ../ -DDEVEL=1 -DCMAKE_BUILD_TYPE=Release -DCMAKE_VERBOSE_MAKEFILE=1 && make -j$(grep -c ^processor /proc/cpuinfo)


